---
name: 'Submit Dependencies'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  build:
    uses: metaborg/workflows/.github/workflows/gradle-dependencies.yaml@main
