---
name: 'Submit Dependencies'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  dependencies:
    uses: metaborg/actions/.github/workflows/gradle-dependencies.yaml@main
